#Animator is basically Skia's (much saner) version of Flash.
#On top of Views it provides a declarative UI model which can be updated
#based on events which trigger changes or scripts.

{
  'includes': [
    'common.gypi',
  ],
  'targets': [
    {
      'target_name': 'animator',
      'type': 'static_library',
      'include_dirs': [
        '../deps/skia/include/config',
        '../deps/skia/include/core',
        '../deps/skia/include/effects',
        '../deps/skia/include/animator',
        '../deps/skia/include/views',
        '../deps/skia/include/xml',
        '../deps/skia/include/utils',
        '../deps/skia/include/images',
        '../deps/skia/src/utils',
      ],
      'sources': [
        '../deps/skia/include/animator/SkAnimator.h',
        '../deps/skia/include/animator/SkAnimatorView.h',

        '../deps/skia/src/animator/SkAnimate.h',
        '../deps/skia/src/animator/SkAnimateActive.cpp',
        '../deps/skia/src/animator/SkAnimateActive.h',
        '../deps/skia/src/animator/SkAnimateBase.cpp',
        '../deps/skia/src/animator/SkAnimateBase.h',
        '../deps/skia/src/animator/SkAnimateField.cpp',
        '../deps/skia/src/animator/SkAnimateMaker.cpp',
        '../deps/skia/src/animator/SkAnimateMaker.h',
        '../deps/skia/src/animator/SkAnimateProperties.h',
        '../deps/skia/src/animator/SkAnimateSet.cpp',
        '../deps/skia/src/animator/SkAnimateSet.h',
        '../deps/skia/src/animator/SkAnimator.cpp',
        '../deps/skia/src/animator/SkAnimatorScript.cpp',
        '../deps/skia/src/animator/SkAnimatorScript.h',
        #'../deps/skia/src/animator/SkAnimatorScript2.cpp', fails on windows
        #'../deps/skia/src/animator/SkAnimatorScript2.h',
        '../deps/skia/src/animator/SkBoundable.cpp',
        '../deps/skia/src/animator/SkBoundable.h',
        '../deps/skia/src/animator/SkBuildCondensedInfo.cpp',
        #'../deps/skia/src/animator/SkCondensedDebug.cpp', fails on windows
        #'../deps/skia/src/animator/SkCondensedRelease.cpp',
        '../deps/skia/src/animator/SkDisplayable.cpp',
        '../deps/skia/src/animator/SkDisplayable.h',
        '../deps/skia/src/animator/SkDisplayAdd.cpp',
        '../deps/skia/src/animator/SkDisplayAdd.h',
        '../deps/skia/src/animator/SkDisplayApply.cpp',
        '../deps/skia/src/animator/SkDisplayApply.h',
        '../deps/skia/src/animator/SkDisplayBounds.cpp',
        '../deps/skia/src/animator/SkDisplayBounds.h',
        '../deps/skia/src/animator/SkDisplayEvent.cpp',
        '../deps/skia/src/animator/SkDisplayEvent.h',
        '../deps/skia/src/animator/SkDisplayEvents.cpp',
        '../deps/skia/src/animator/SkDisplayEvents.h',
        '../deps/skia/src/animator/SkDisplayInclude.cpp',
        '../deps/skia/src/animator/SkDisplayInclude.h',
        '../deps/skia/src/animator/SkDisplayInput.cpp',
        '../deps/skia/src/animator/SkDisplayInput.h',
        '../deps/skia/src/animator/SkDisplayList.cpp',
        '../deps/skia/src/animator/SkDisplayList.h',
        '../deps/skia/src/animator/SkDisplayMath.cpp',
        '../deps/skia/src/animator/SkDisplayMath.h',
        '../deps/skia/src/animator/SkDisplayMovie.cpp',
        '../deps/skia/src/animator/SkDisplayMovie.h',
        '../deps/skia/src/animator/SkDisplayNumber.cpp',
        '../deps/skia/src/animator/SkDisplayNumber.h',
        '../deps/skia/src/animator/SkDisplayPost.cpp',
        '../deps/skia/src/animator/SkDisplayPost.h',
        '../deps/skia/src/animator/SkDisplayRandom.cpp',
        '../deps/skia/src/animator/SkDisplayRandom.h',
        '../deps/skia/src/animator/SkDisplayScreenplay.cpp',
        '../deps/skia/src/animator/SkDisplayScreenplay.h',
        '../deps/skia/src/animator/SkDisplayType.cpp',
        '../deps/skia/src/animator/SkDisplayType.h',
        '../deps/skia/src/animator/SkDisplayTypes.cpp',
        '../deps/skia/src/animator/SkDisplayTypes.h',
        '../deps/skia/src/animator/SkDisplayXMLParser.cpp',
        '../deps/skia/src/animator/SkDisplayXMLParser.h',
        '../deps/skia/src/animator/SkDraw3D.cpp',
        '../deps/skia/src/animator/SkDraw3D.h',
        '../deps/skia/src/animator/SkDrawable.cpp',
        '../deps/skia/src/animator/SkDrawable.h',
        '../deps/skia/src/animator/SkDrawBitmap.cpp',
        '../deps/skia/src/animator/SkDrawBitmap.h',
        '../deps/skia/src/animator/SkDrawBlur.cpp',
        '../deps/skia/src/animator/SkDrawBlur.h',
        '../deps/skia/src/animator/SkDrawClip.cpp',
        '../deps/skia/src/animator/SkDrawClip.h',
        '../deps/skia/src/animator/SkDrawColor.cpp',
        '../deps/skia/src/animator/SkDrawColor.h',
        '../deps/skia/src/animator/SkDrawDash.cpp',
        '../deps/skia/src/animator/SkDrawDash.h',
        '../deps/skia/src/animator/SkDrawDiscrete.cpp',
        '../deps/skia/src/animator/SkDrawDiscrete.h',
        '../deps/skia/src/animator/SkDrawEmboss.cpp',
        '../deps/skia/src/animator/SkDrawEmboss.h',
        '../deps/skia/src/animator/SkDrawExtraPathEffect.cpp',
        '../deps/skia/src/animator/SkDrawFull.cpp',
        '../deps/skia/src/animator/SkDrawFull.h',
        '../deps/skia/src/animator/SkDrawGradient.cpp',
        '../deps/skia/src/animator/SkDrawGradient.h',
        '../deps/skia/src/animator/SkDrawGroup.cpp',
        '../deps/skia/src/animator/SkDrawGroup.h',
        '../deps/skia/src/animator/SkDrawLine.cpp',
        '../deps/skia/src/animator/SkDrawLine.h',
        '../deps/skia/src/animator/SkDrawMatrix.cpp',
        '../deps/skia/src/animator/SkDrawMatrix.h',
        '../deps/skia/src/animator/SkDrawOval.cpp',
        '../deps/skia/src/animator/SkDrawOval.h',
        '../deps/skia/src/animator/SkDrawPaint.cpp',
        '../deps/skia/src/animator/SkDrawPaint.h',
        '../deps/skia/src/animator/SkDrawPath.cpp',
        '../deps/skia/src/animator/SkDrawPath.h',
        '../deps/skia/src/animator/SkDrawPoint.cpp',
        '../deps/skia/src/animator/SkDrawPoint.h',
        '../deps/skia/src/animator/SkDrawRectangle.cpp',
        '../deps/skia/src/animator/SkDrawRectangle.h',
        '../deps/skia/src/animator/SkDrawSaveLayer.cpp',
        '../deps/skia/src/animator/SkDrawSaveLayer.h',
        '../deps/skia/src/animator/SkDrawShader.cpp',
        '../deps/skia/src/animator/SkDrawShader.h',
        '../deps/skia/src/animator/SkDrawText.cpp',
        '../deps/skia/src/animator/SkDrawText.h',
        '../deps/skia/src/animator/SkDrawTextBox.cpp',
        '../deps/skia/src/animator/SkDrawTextBox.h',
        '../deps/skia/src/animator/SkDrawTo.cpp',
        '../deps/skia/src/animator/SkDrawTo.h',
        '../deps/skia/src/animator/SkDrawTransparentShader.cpp',
        '../deps/skia/src/animator/SkDrawTransparentShader.h',
        '../deps/skia/src/animator/SkDump.cpp',
        '../deps/skia/src/animator/SkDump.h',
        '../deps/skia/src/animator/SkExtras.h',
        '../deps/skia/src/animator/SkGetCondensedInfo.cpp',
        '../deps/skia/src/animator/SkHitClear.cpp',
        '../deps/skia/src/animator/SkHitClear.h',
        '../deps/skia/src/animator/SkHitTest.cpp',
        '../deps/skia/src/animator/SkHitTest.h',
        '../deps/skia/src/animator/SkIntArray.h',
        '../deps/skia/src/animator/SkMatrixParts.cpp',
        '../deps/skia/src/animator/SkMatrixParts.h',
        '../deps/skia/src/animator/SkMemberInfo.cpp',
        '../deps/skia/src/animator/SkMemberInfo.h',
        '../deps/skia/src/animator/SkOpArray.cpp',
        '../deps/skia/src/animator/SkOpArray.h',
        '../deps/skia/src/animator/SkOperand.h',
        '../deps/skia/src/animator/SkOperand2.h',
        '../deps/skia/src/animator/SkOperandInterpolator.h',
        '../deps/skia/src/animator/SkOperandIterpolator.cpp',
        '../deps/skia/src/animator/SkPaintParts.cpp',
        '../deps/skia/src/animator/SkPaintParts.h',
        '../deps/skia/src/animator/SkParseSVGPath.cpp',
        '../deps/skia/src/animator/SkPathParts.cpp',
        '../deps/skia/src/animator/SkPathParts.h',
        '../deps/skia/src/animator/SkPostParts.cpp',
        '../deps/skia/src/animator/SkPostParts.h',
        '../deps/skia/src/animator/SkScript.cpp',
        '../deps/skia/src/animator/SkScript.h',
        '../deps/skia/src/animator/SkScript2.h',
        '../deps/skia/src/animator/SkScriptCallBack.h',
        '../deps/skia/src/animator/SkScriptDecompile.cpp',
        '../deps/skia/src/animator/SkScriptRuntime.cpp',
        '../deps/skia/src/animator/SkScriptRuntime.h',
        '../deps/skia/src/animator/SkScriptTokenizer.cpp',
        '../deps/skia/src/animator/SkSnapshot.cpp',
        '../deps/skia/src/animator/SkSnapshot.h',
        '../deps/skia/src/animator/SkTDArray_Experimental.h',
        '../deps/skia/src/animator/SkTextOnPath.cpp',
        '../deps/skia/src/animator/SkTextOnPath.h',
        '../deps/skia/src/animator/SkTextToPath.cpp',
        '../deps/skia/src/animator/SkTextToPath.h',
        '../deps/skia/src/animator/SkTime.cpp',
        '../deps/skia/src/animator/SkTypedArray.cpp',
        '../deps/skia/src/animator/SkTypedArray.h',
        '../deps/skia/src/animator/SkXMLAnimatorWriter.cpp',
        '../deps/skia/src/animator/SkXMLAnimatorWriter.h',
      ],
      'direct_dependent_settings': {
        'include_dirs': [
          '../deps/skia/include/animator',
        ],
      },
    },
  ],
}

# Local Variables:
# tab-width:2
# indent-tabs-mode:nil
# End:
# vim: set expandtab tabstop=2 shiftwidth=2:
