# Core Skia library code.
{
  'includes': [
    'common.gypi'
  ],
  'targets': [
    {
      'target_name': 'core',
      'type': 'static_library',
      'msvs_guid': 'B7760B5E-BFA8-486B-ACFD-49E3A6DE8E76',
      'sources': [
        '../deps/skia/src/core/ARGB32_Clamp_Bilinear_BitmapShader.h',
        '../deps/skia/src/core/Sk64.cpp',
        '../deps/skia/src/core/SkAAClip.cpp',
        '../deps/skia/src/core/SkAnnotation.cpp',
        '../deps/skia/src/core/SkAdvancedTypefaceMetrics.cpp',
        '../deps/skia/src/core/SkAlphaRuns.cpp',
        '../deps/skia/src/core/SkAntiRun.h',
        '../deps/skia/src/core/SkBitmap.cpp',
        '../deps/skia/src/core/SkBitmapProcShader.cpp',
        '../deps/skia/src/core/SkBitmapProcShader.h',
        '../deps/skia/src/core/SkBitmapProcState.cpp',
        '../deps/skia/src/core/SkBitmapProcState.h',
        '../deps/skia/src/core/SkBitmapProcState_matrix.h',
        '../deps/skia/src/core/SkBitmapProcState_matrixProcs.cpp',
        '../deps/skia/src/core/SkBitmapProcState_sample.h',
        '../deps/skia/src/core/SkBitmapSampler.cpp',
        '../deps/skia/src/core/SkBitmapSampler.h',
        '../deps/skia/src/core/SkBitmapSamplerTemplate.h',
        '../deps/skia/src/core/SkBitmapShader16BilerpTemplate.h',
        '../deps/skia/src/core/SkBitmapShaderTemplate.h',
        '../deps/skia/src/core/SkBitmap_scroll.cpp',
        '../deps/skia/src/core/SkBlitBWMaskTemplate.h',
        '../deps/skia/src/core/SkBlitMask_D32.cpp',
        '../deps/skia/src/core/SkBlitRow_D16.cpp',
        '../deps/skia/src/core/SkBlitRow_D32.cpp',
        '../deps/skia/src/core/SkBlitRow_D4444.cpp',
        '../deps/skia/src/core/SkBlitter.cpp',
        '../deps/skia/src/core/SkBlitter_4444.cpp',
        '../deps/skia/src/core/SkBlitter_A1.cpp',
        '../deps/skia/src/core/SkBlitter_A8.cpp',
        '../deps/skia/src/core/SkBlitter_ARGB32.cpp',
        '../deps/skia/src/core/SkBlitter_RGB16.cpp',
        '../deps/skia/src/core/SkBlitter_Sprite.cpp',
        '../deps/skia/src/core/SkBuffer.cpp',
        '../deps/skia/src/core/SkCanvas.cpp',
        '../deps/skia/src/core/SkChunkAlloc.cpp',
        '../deps/skia/src/core/SkClipStack.cpp',
        '../deps/skia/src/core/SkColor.cpp',
        '../deps/skia/src/core/SkColorFilter.cpp',
        '../deps/skia/src/core/SkColorTable.cpp',
        '../deps/skia/src/core/SkComposeShader.cpp',
        '../deps/skia/src/core/SkConcaveToTriangles.cpp',
        '../deps/skia/src/core/SkConcaveToTriangles.h',
        '../deps/skia/src/core/SkConfig8888.cpp',
        '../deps/skia/src/core/SkConfig8888.h',
        '../deps/skia/src/core/SkCordic.cpp',
        '../deps/skia/src/core/SkCordic.h',
        '../deps/skia/src/core/SkCoreBlitters.h',
        '../deps/skia/src/core/SkCubicClipper.cpp',
        '../deps/skia/src/core/SkCubicClipper.h',
        '../deps/skia/src/core/SkData.cpp',
        '../deps/skia/src/core/SkDebug.cpp',
        '../deps/skia/src/core/SkDeque.cpp',
        '../deps/skia/src/core/SkDevice.cpp',
        '../deps/skia/src/core/SkDeviceProfile.cpp',
        '../deps/skia/src/core/SkDither.cpp',
        '../deps/skia/src/core/SkDraw.cpp',
        '../deps/skia/src/core/SkDrawProcs.h',
        '../deps/skia/src/core/SkEdgeBuilder.cpp',
        '../deps/skia/src/core/SkEdgeClipper.cpp',
        '../deps/skia/src/core/SkEdge.cpp',
        '../deps/skia/src/core/SkEdge.h',
        '../deps/skia/src/core/SkFP.h',
        '../deps/skia/src/core/SkFilterProc.cpp',
        '../deps/skia/src/core/SkFilterProc.h',
        '../deps/skia/src/core/SkFlattenable.cpp',
        '../deps/skia/src/core/SkFloat.cpp',
        '../deps/skia/src/core/SkFloat.h',
        '../deps/skia/src/core/SkFloatBits.cpp',
        '../deps/skia/src/core/SkFontHost.cpp',
        '../deps/skia/src/core/SkGeometry.cpp',
        '../deps/skia/src/core/SkGlyphCache.cpp',
        '../deps/skia/src/core/SkGlyphCache.h',
        '../deps/skia/src/core/SkGraphics.cpp',
        '../deps/skia/src/core/SkInstCnt.cpp',
        '../deps/skia/src/core/SkLineClipper.cpp',
        '../deps/skia/src/core/SkMallocPixelRef.cpp',
        '../deps/skia/src/core/SkMask.cpp',
        '../deps/skia/src/core/SkMaskFilter.cpp',
        '../deps/skia/src/core/SkMaskGamma.cpp',
        '../deps/skia/src/core/SkMaskGamma.h',
        '../deps/skia/src/core/SkMath.cpp',
        '../deps/skia/src/core/SkMatrix.cpp',
        '../deps/skia/src/core/SkMetaData.cpp',
        '../deps/skia/src/core/SkMMapStream.cpp',
        '../deps/skia/src/core/SkOrderedReadBuffer.cpp',
        '../deps/skia/src/core/SkOrderedWriteBuffer.cpp',
        '../deps/skia/src/core/SkPackBits.cpp',
        '../deps/skia/src/core/SkPaint.cpp',
        '../deps/skia/src/core/SkPath.cpp',
        '../deps/skia/src/core/SkPathEffect.cpp',
        '../deps/skia/src/core/SkPathHeap.cpp',
        '../deps/skia/src/core/SkPathHeap.h',
        '../deps/skia/src/core/SkPathMeasure.cpp',
        '../deps/skia/src/core/SkPicture.cpp',
        '../deps/skia/src/core/SkPictureFlat.cpp',
        '../deps/skia/src/core/SkPictureFlat.h',
        '../deps/skia/src/core/SkPicturePlayback.cpp',
        '../deps/skia/src/core/SkPicturePlayback.h',
        '../deps/skia/src/core/SkPictureRecord.cpp',
        '../deps/skia/src/core/SkPictureRecord.h',
        '../deps/skia/src/core/SkPixelRef.cpp',
        '../deps/skia/src/core/SkPoint.cpp',
        '../deps/skia/src/core/SkProcSpriteBlitter.cpp',
        '../deps/skia/src/core/SkPtrRecorder.cpp',
        '../deps/skia/src/core/SkQuadClipper.cpp',
        '../deps/skia/src/core/SkQuadClipper.h',
        '../deps/skia/src/core/SkRasterClip.cpp',
        '../deps/skia/src/core/SkRasterizer.cpp',
        '../deps/skia/src/core/SkRect.cpp',
        '../deps/skia/src/core/SkRefCnt.cpp',
        '../deps/skia/src/core/SkRefDict.cpp',
        '../deps/skia/src/core/SkRegion.cpp',
        '../deps/skia/src/core/SkRegionPriv.h',
        '../deps/skia/src/core/SkRegion_path.cpp',
        '../deps/skia/src/core/SkScalar.cpp',
        '../deps/skia/src/core/SkScalerContext.cpp',
        '../deps/skia/src/core/SkScan.cpp',
        '../deps/skia/src/core/SkScanPriv.h',
        '../deps/skia/src/core/SkScan_AntiPath.cpp',
        '../deps/skia/src/core/SkScan_Antihair.cpp',
        '../deps/skia/src/core/SkScan_Hairline.cpp',
        '../deps/skia/src/core/SkScan_Path.cpp',
        '../deps/skia/src/core/SkShader.cpp',
        '../deps/skia/src/core/SkShape.cpp',
        '../deps/skia/src/core/SkSpriteBlitter_ARGB32.cpp',
        '../deps/skia/src/core/SkSpriteBlitter_RGB16.cpp',
        '../deps/skia/src/core/SkSinTable.h',
        '../deps/skia/src/core/SkSpriteBlitter.h',
        '../deps/skia/src/core/SkSpriteBlitterTemplate.h',
        '../deps/skia/src/core/SkStream.cpp',
        '../deps/skia/src/core/SkString.cpp',
        '../deps/skia/src/core/SkStroke.h',
        '../deps/skia/src/core/SkStroke.cpp',
        '../deps/skia/src/core/SkStrokerPriv.cpp',
        '../deps/skia/src/core/SkStrokerPriv.h',
        '../deps/skia/src/core/SkTextFormatParams.h',
        '../deps/skia/src/core/SkTLS.cpp',
        '../deps/skia/src/core/SkTSearch.cpp',
        '../deps/skia/src/core/SkTSort.h',
        '../deps/skia/src/core/SkTemplatesPriv.h',
        '../deps/skia/src/core/SkTypeface.cpp',
        '../deps/skia/src/core/SkTypefaceCache.cpp',
        '../deps/skia/src/core/SkTypefaceCache.h',
        '../deps/skia/src/core/SkUnPreMultiply.cpp',
        '../deps/skia/src/core/SkUtils.cpp',
        '../deps/skia/src/core/SkWriter32.cpp',
        '../deps/skia/src/core/SkXfermode.cpp',
        '../deps/skia/src/pipe/SkGPipeRead.cpp',
        '../deps/skia/src/pipe/SkGPipeWrite.cpp',

        '../deps/skia/include/core/Sk64.h',
        '../deps/skia/include/core/SkAdvancedTypefaceMetrics.h',
        '../deps/skia/include/core/SkAutoKern.h',
        '../deps/skia/include/core/SkBitmap.h',
        '../deps/skia/include/core/SkBlitRow.h',
        '../deps/skia/include/core/SkBlitter.h',
        '../deps/skia/include/core/SkBounder.h',
        '../deps/skia/include/core/SkBuffer.h',
        '../deps/skia/include/core/SkCanvas.h',
        '../deps/skia/include/core/SkChecksum.h',
        '../deps/skia/include/core/SkChunkAlloc.h',
        '../deps/skia/include/core/SkClipStack.h',
        '../deps/skia/include/core/SkColor.h',
        '../deps/skia/include/core/SkColorFilter.h',
        '../deps/skia/include/core/SkColorPriv.h',
        '../deps/skia/include/core/SkColorShader.h',
        '../deps/skia/include/core/SkComposeShader.h',
        '../deps/skia/include/core/SkData.h',
        '../deps/skia/include/core/SkDeque.h',
        '../deps/skia/include/core/SkDescriptor.h',
        '../deps/skia/include/core/SkDevice.h',
        '../deps/skia/include/core/SkDither.h',
        '../deps/skia/include/core/SkDraw.h',
        '../deps/skia/include/core/SkDrawFilter.h',
        '../deps/skia/include/core/SkDrawLooper.h',
        '../deps/skia/include/core/SkEndian.h',
        '../deps/skia/include/core/SkFDot6.h',
        '../deps/skia/include/core/SkFixed.h',
        '../deps/skia/include/core/SkFlattenable.h',
        '../deps/skia/include/core/SkFloatBits.h',
        '../deps/skia/include/core/SkFloatingPoint.h',
        '../deps/skia/include/core/SkFontHost.h',
        '../deps/skia/include/core/SkGeometry.h',
        '../deps/skia/include/core/SkGlyph.h',
        '../deps/skia/include/core/SkGraphics.h',
        '../deps/skia/include/core/SkInstCnt.h',
        '../deps/skia/include/core/SkMallocPixelRef.h',
        '../deps/skia/include/core/SkMask.h',
        '../deps/skia/include/core/SkMaskFilter.h',
        '../deps/skia/include/core/SkMath.h',
        '../deps/skia/include/core/SkMatrix.h',
        '../deps/skia/include/core/SkMetaData.h',
        '../deps/skia/include/core/SkMMapStream.h',
        '../deps/skia/include/core/SkOSFile.h',
        '../deps/skia/include/core/SkPackBits.h',
        '../deps/skia/include/core/SkPaint.h',
        '../deps/skia/include/core/SkPath.h',
        '../deps/skia/include/core/SkPathEffect.h',
        '../deps/skia/include/core/SkPathMeasure.h',
        '../deps/skia/include/core/SkPerspIter.h',
        '../deps/skia/include/core/SkPicture.h',
        '../deps/skia/include/core/SkPixelRef.h',
        '../deps/skia/include/core/SkPoint.h',
        '../deps/skia/include/core/SkPtrRecorder.h',
        '../deps/skia/include/core/SkRandom.h',
        '../deps/skia/include/core/SkRasterizer.h',
        '../deps/skia/include/core/SkReader32.h',
        '../deps/skia/include/core/SkRect.h',
        '../deps/skia/include/core/SkRefCnt.h',
        '../deps/skia/include/core/SkRefDict.h',
        '../deps/skia/include/core/SkRegion.h',
        '../deps/skia/include/core/SkScalar.h',
        '../deps/skia/include/core/SkScalarCompare.h',
        '../deps/skia/include/core/SkScalerContext.h',
        '../deps/skia/include/core/SkScan.h',
        '../deps/skia/include/core/SkShader.h',
        '../deps/skia/include/core/SkStream.h',
        '../deps/skia/include/core/SkString.h',
        '../deps/skia/include/core/SkTArray.h',
        '../deps/skia/include/core/SkTDArray.h',
        '../deps/skia/include/core/SkTDStack.h',
        '../deps/skia/include/core/SkTDict.h',
        '../deps/skia/include/core/SkTRegistry.h',
        '../deps/skia/include/core/SkTScopedPtr.h',
        '../deps/skia/include/core/SkTSearch.h',
        '../deps/skia/include/core/SkTemplates.h',
        '../deps/skia/include/core/SkThread.h',
        '../deps/skia/include/core/SkThread_platform.h',
        '../deps/skia/include/core/SkTime.h',
        '../deps/skia/include/core/SkTLazy.h',
        '../deps/skia/include/core/SkTrace.h',
        '../deps/skia/include/core/SkTypeface.h',
        '../deps/skia/include/core/SkTypes.h',
        '../deps/skia/include/core/SkUnPreMultiply.h',
        '../deps/skia/include/core/SkUnitMapper.h',
        '../deps/skia/include/core/SkUtils.h',
        '../deps/skia/include/core/SkWeakRefCnt.h',
        '../deps/skia/include/core/SkWriter32.h',
        '../deps/skia/include/core/SkXfermode.h',
      ],
      'include_dirs': [
        '../deps/skia/include/config',
        '../deps/skia/include/core',
        '../deps/skia/include/pipe',
        '../deps/skia/include/ports',
        '../deps/skia/include/xml',
        '../deps/skia/src/core',
      ],
      'msvs_disabled_warnings': [4244, 4267,4345, 4390, 4554, 4800],
      'conditions': [
        [ 'skia_os in ["linux", "freebsd", "openbsd", "solaris"]', {
          'cflags': [
            '-Wno-unused',
            '-Wno-unused-function',
          ],
          'link_settings': {
            'libraries': [
              '-lfreetype',
              '-lpthread',
            ],
          },
        }],
        [ 'skia_os == "mac"', {
          'include_dirs': [
            '../deps/skia/include/utils/mac',
            '../deps/skia/third_party/freetype/include/**',
          ],
          'sources': [
            '../deps/skia/include/utils/mac/SkCGUtils.h',
          ],
          'link_settings': {
            'libraries': [
              '$(SDKROOT)/System/Library/Frameworks/ApplicationServices.framework',
            ],
          },
        }],
        [ 'skia_os == "ios"', {
          'include_dirs': [
            '../deps/skia/include/utils/ios',
          ],
          'sources': [
            '../deps/skia/include/utils/mac/SkCGUtils.h',
          ],
          'link_settings': {
            'libraries': [
              '/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS4.3.sdk/System/Library/Frameworks/CoreFoundation.framework',
              '/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS4.3.sdk/System/Library/Frameworks/CoreGraphics.framework',
              '/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS4.3.sdk/System/Library/Frameworks/CoreText.framework',
              '/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS4.3.sdk/System/Library/Frameworks/UIKit.framework',
              '/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS4.3.sdk/System/Library/Frameworks/Foundation.framework',
              '/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS4.3.sdk/System/Library/Frameworks/QuartzCore.framework',
              '/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS4.3.sdk/System/Library/Frameworks/OpenGLES.framework',
            ],
          },
        }],
        [ 'skia_os == "win"', {
          'include_dirs': [
            'config/win',
          ],
          'sources!': [
            '../deps/skia/include/core/SkMMapStream.h',
            '../deps/skia/src/core/SkMMapStream.cpp',
          ],
        }],
        [ 'skia_os == "android"', {
          'dependencies': [
             'android_system.gyp:ft2',
          ],
        }],
        [ 'skia_os == "android" and skia_arch_type == "arm" and armv7 == 1', {
          # The code in SkUtilsArm.cpp can be used on an ARM-based Linux system, not only Android.
          'sources': [
            '../deps/skia/src/core/SkUtilsArm.cpp',
            '../deps/skia/src/core/SkUtilsArm.h',
          ],
        }],
      ],
      'direct_dependent_settings': {
        'include_dirs': [
          'config',
          '../deps/skia/include/config',
          '../deps/skia/include/core',
          '../deps/skia/include/pipe',
          'ext',
        ],
      },
      'dependencies': [
        'opts.gyp:opts'
      ],
    },
  ],
}

# Local Variables:
# tab-width:2
# indent-tabs-mode:nil
# End:
# vim: set expandtab tabstop=2 shiftwidth=2:
